// <auto-generated />
using Isjr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Isjr.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171211083408_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Isjr.Data.Enitites.JojoReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("OriginalId");

                    b.Property<int?>("ReferenceId");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.HasIndex("OriginalId");

                    b.HasIndex("ReferenceId");

                    b.ToTable("JojoReferences");
                });

            modelBuilder.Entity("Isjr.Data.Enitites.MultimediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("TypeId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("MultimediaItems");
                });

            modelBuilder.Entity("Isjr.Data.Enitites.MultimediaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("MultimediaTypes");
                });

            modelBuilder.Entity("Isjr.Data.Enitites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Hash")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Isjr.Data.Enitites.JojoReference", b =>
                {
                    b.HasOne("Isjr.Data.Enitites.MultimediaItem", "Original")
                        .WithMany()
                        .HasForeignKey("OriginalId");

                    b.HasOne("Isjr.Data.Enitites.MultimediaItem", "Reference")
                        .WithMany()
                        .HasForeignKey("ReferenceId");
                });

            modelBuilder.Entity("Isjr.Data.Enitites.MultimediaItem", b =>
                {
                    b.HasOne("Isjr.Data.Enitites.MultimediaType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
